% Rule 5
% Rule 6
constraint c_1_0=-18 -> true;
constraint c_1_0=-19 -> true;
constraint c_1_0=-20 -> true;
constraint c_1_0=-7 -> true;
constraint c_1_0=-8 -> true;
constraint c_1_0=-9 -> true;
constraint c_1_0=-12 -> true;
constraint c_1_0=-13 -> true;
constraint c_1_0=-14 -> true;
constraint c_1_0=-15 -> true;
constraint c_1_0=-16 -> true;
% Rule 6
constraint c_1_1=-17 -> true;
constraint c_1_1=-21 -> true;
constraint c_1_1=-10 -> true;
% Rule 6
constraint c_1_2=-7 -> true;
constraint c_1_2=-8 -> true;
constraint c_1_2=-9 -> true;
% Rule 6
constraint c_1_3=-11 -> true;
% Rule 6
constraint c_1_4=-18 -> true;
constraint c_1_4=-19 -> true;
constraint c_1_4=-20 -> true;
constraint c_1_4=-7 -> true;
constraint c_1_4=-8 -> true;
constraint c_1_4=-9 -> true;
constraint c_1_4=-12 -> true;
constraint c_1_4=-13 -> true;
constraint c_1_4=-14 -> true;
constraint c_1_4=-15 -> true;
constraint c_1_4=-16 -> true;
% Rule 6
constraint c_1_5=-22 -> true;
constraint c_1_5=-24 -> true;
constraint c_1_5=-25 -> true;
% Rule 6
constraint c_1_6=-18 -> true;
constraint c_1_6=-19 -> true;
constraint c_1_6=-20 -> true;
% Rule 6
constraint c_1_7=-23 -> true;
% Rule 8
constraint (p_1_0_2=0/\p_1_1_2!=0)->c_1_0<0;
constraint (p_1_0_2!=0/\p_1_1_2=0)->c_1_0<0;

constraint (p_1_0_2=1/\p_1_1_2!=1)->c_1_0<0;
constraint (p_1_0_2!=1/\p_1_1_2=1)->c_1_0<0;

constraint (p_1_0_2=2/\p_1_1_2!=2)->c_1_0<0;
constraint (p_1_0_2!=2/\p_1_1_2=2)->c_1_0<0;

constraint (p_1_0_0=3/\p_1_1_0!=3)->c_1_0<0;
constraint (p_1_0_0!=3/\p_1_1_0=3)->c_1_0<0;

constraint (p_1_0_3=4/\p_1_1_3!=4)->c_1_0<0;
constraint (p_1_0_3!=4/\p_1_1_3=4)->c_1_0<0;

constraint (p_1_0_0=5/\p_1_1_0!=5)->c_1_0<0;
constraint (p_1_0_0!=5/\p_1_1_0=5)->c_1_0<0;

constraint (p_1_0_3=6/\p_1_1_3!=6)->c_1_0<0;
constraint (p_1_0_3!=6/\p_1_1_3=6)->c_1_0<0;

constraint (p_1_0_1=7/\p_1_1_1!=7)->c_1_0<0;
constraint (p_1_0_1!=7/\p_1_1_1=7)->c_1_0<0;

constraint (p_1_0_1=8/\p_1_1_1!=8)->c_1_0<0;
constraint (p_1_0_1!=8/\p_1_1_1=8)->c_1_0<0;

constraint (p_1_0_0=9/\p_1_1_0!=9)->c_1_0<0;
constraint (p_1_0_0!=9/\p_1_1_0=9)->c_1_0<0;

constraint (p_1_0_1=10/\p_1_1_1!=10)->c_1_0<0;
constraint (p_1_0_1!=10/\p_1_1_1=10)->c_1_0<0;

constraint (p_1_0_0=11/\p_1_1_0!=11)->c_1_0<0;
constraint (p_1_0_0!=11/\p_1_1_0=11)->c_1_0<0;

constraint (p_1_0_1=12/\p_1_1_1!=12)->c_1_0<0;
constraint (p_1_0_1!=12/\p_1_1_1=12)->c_1_0<0;

constraint (p_1_0_4=13/\p_1_1_4!=13)->c_1_0<0;
constraint (p_1_0_4!=13/\p_1_1_4=13)->c_1_0<0;

constraint (p_1_0_5=14/\p_1_1_5!=14)->c_1_0<0;
constraint (p_1_0_5!=14/\p_1_1_5=14)->c_1_0<0;

constraint (p_1_0_6=15/\p_1_1_6!=15)->c_1_0<0;
constraint (p_1_0_6!=15/\p_1_1_6=15)->c_1_0<0;

constraint (p_1_0_7=16/\p_1_1_7!=16)->c_1_0<0;
constraint (p_1_0_7!=16/\p_1_1_7=16)->c_1_0<0;

constraint (p_1_0_8=17/\p_1_1_8!=17)->c_1_0<0;
constraint (p_1_0_8!=17/\p_1_1_8=17)->c_1_0<0;

% Rule 8
constraint (p_1_1_2=0/\p_1_2_2!=0)->c_1_1<0;
constraint (p_1_1_2!=0/\p_1_2_2=0)->c_1_1<0;

constraint (p_1_1_2=1/\p_1_2_2!=1)->c_1_1<0;
constraint (p_1_1_2!=1/\p_1_2_2=1)->c_1_1<0;

constraint (p_1_1_2=2/\p_1_2_2!=2)->c_1_1<0;
constraint (p_1_1_2!=2/\p_1_2_2=2)->c_1_1<0;

constraint (p_1_1_0=3/\p_1_2_0!=3)->c_1_1<0;
constraint (p_1_1_0!=3/\p_1_2_0=3)->c_1_1<0;

constraint (p_1_1_3=4/\p_1_2_3!=4)->c_1_1<0;
constraint (p_1_1_3!=4/\p_1_2_3=4)->c_1_1<0;

constraint (p_1_1_0=5/\p_1_2_0!=5)->c_1_1<0;
constraint (p_1_1_0!=5/\p_1_2_0=5)->c_1_1<0;

constraint (p_1_1_3=6/\p_1_2_3!=6)->c_1_1<0;
constraint (p_1_1_3!=6/\p_1_2_3=6)->c_1_1<0;

constraint (p_1_1_1=7/\p_1_2_1!=7)->c_1_1<0;
constraint (p_1_1_1!=7/\p_1_2_1=7)->c_1_1<0;

constraint (p_1_1_1=8/\p_1_2_1!=8)->c_1_1<0;
constraint (p_1_1_1!=8/\p_1_2_1=8)->c_1_1<0;

constraint (p_1_1_0=9/\p_1_2_0!=9)->c_1_1<0;
constraint (p_1_1_0!=9/\p_1_2_0=9)->c_1_1<0;

constraint (p_1_1_1=10/\p_1_2_1!=10)->c_1_1<0;
constraint (p_1_1_1!=10/\p_1_2_1=10)->c_1_1<0;

constraint (p_1_1_0=11/\p_1_2_0!=11)->c_1_1<0;
constraint (p_1_1_0!=11/\p_1_2_0=11)->c_1_1<0;

constraint (p_1_1_1=12/\p_1_2_1!=12)->c_1_1<0;
constraint (p_1_1_1!=12/\p_1_2_1=12)->c_1_1<0;

constraint (p_1_1_4=13/\p_1_2_4!=13)->c_1_1<0;
constraint (p_1_1_4!=13/\p_1_2_4=13)->c_1_1<0;

constraint (p_1_1_5=14/\p_1_2_5!=14)->c_1_1<0;
constraint (p_1_1_5!=14/\p_1_2_5=14)->c_1_1<0;

constraint (p_1_1_6=15/\p_1_2_6!=15)->c_1_1<0;
constraint (p_1_1_6!=15/\p_1_2_6=15)->c_1_1<0;

constraint (p_1_1_7=16/\p_1_2_7!=16)->c_1_1<0;
constraint (p_1_1_7!=16/\p_1_2_7=16)->c_1_1<0;

constraint (p_1_1_8=17/\p_1_2_8!=17)->c_1_1<0;
constraint (p_1_1_8!=17/\p_1_2_8=17)->c_1_1<0;

% Rule 8
constraint (p_1_2_2=0/\p_1_3_2!=0)->c_1_2<0;
constraint (p_1_2_2!=0/\p_1_3_2=0)->c_1_2<0;

constraint (p_1_2_2=1/\p_1_3_2!=1)->c_1_2<0;
constraint (p_1_2_2!=1/\p_1_3_2=1)->c_1_2<0;

constraint (p_1_2_2=2/\p_1_3_2!=2)->c_1_2<0;
constraint (p_1_2_2!=2/\p_1_3_2=2)->c_1_2<0;

constraint (p_1_2_0=3/\p_1_3_0!=3)->c_1_2<0;
constraint (p_1_2_0!=3/\p_1_3_0=3)->c_1_2<0;

constraint (p_1_2_3=4/\p_1_3_3!=4)->c_1_2<0;
constraint (p_1_2_3!=4/\p_1_3_3=4)->c_1_2<0;

constraint (p_1_2_0=5/\p_1_3_0!=5)->c_1_2<0;
constraint (p_1_2_0!=5/\p_1_3_0=5)->c_1_2<0;

constraint (p_1_2_3=6/\p_1_3_3!=6)->c_1_2<0;
constraint (p_1_2_3!=6/\p_1_3_3=6)->c_1_2<0;

constraint (p_1_2_1=7/\p_1_3_1!=7)->c_1_2<0;
constraint (p_1_2_1!=7/\p_1_3_1=7)->c_1_2<0;

constraint (p_1_2_1=8/\p_1_3_1!=8)->c_1_2<0;
constraint (p_1_2_1!=8/\p_1_3_1=8)->c_1_2<0;

constraint (p_1_2_0=9/\p_1_3_0!=9)->c_1_2<0;
constraint (p_1_2_0!=9/\p_1_3_0=9)->c_1_2<0;

constraint (p_1_2_1=10/\p_1_3_1!=10)->c_1_2<0;
constraint (p_1_2_1!=10/\p_1_3_1=10)->c_1_2<0;

constraint (p_1_2_0=11/\p_1_3_0!=11)->c_1_2<0;
constraint (p_1_2_0!=11/\p_1_3_0=11)->c_1_2<0;

constraint (p_1_2_1=12/\p_1_3_1!=12)->c_1_2<0;
constraint (p_1_2_1!=12/\p_1_3_1=12)->c_1_2<0;

constraint (p_1_2_4=13/\p_1_3_4!=13)->c_1_2<0;
constraint (p_1_2_4!=13/\p_1_3_4=13)->c_1_2<0;

constraint (p_1_2_5=14/\p_1_3_5!=14)->c_1_2<0;
constraint (p_1_2_5!=14/\p_1_3_5=14)->c_1_2<0;

constraint (p_1_2_6=15/\p_1_3_6!=15)->c_1_2<0;
constraint (p_1_2_6!=15/\p_1_3_6=15)->c_1_2<0;

constraint (p_1_2_7=16/\p_1_3_7!=16)->c_1_2<0;
constraint (p_1_2_7!=16/\p_1_3_7=16)->c_1_2<0;

constraint (p_1_2_8=17/\p_1_3_8!=17)->c_1_2<0;
constraint (p_1_2_8!=17/\p_1_3_8=17)->c_1_2<0;

% Rule 8
constraint (p_1_3_2=0/\p_1_4_2!=0)->c_1_3<0;
constraint (p_1_3_2!=0/\p_1_4_2=0)->c_1_3<0;

constraint (p_1_3_2=1/\p_1_4_2!=1)->c_1_3<0;
constraint (p_1_3_2!=1/\p_1_4_2=1)->c_1_3<0;

constraint (p_1_3_2=2/\p_1_4_2!=2)->c_1_3<0;
constraint (p_1_3_2!=2/\p_1_4_2=2)->c_1_3<0;

constraint (p_1_3_0=3/\p_1_4_0!=3)->c_1_3<0;
constraint (p_1_3_0!=3/\p_1_4_0=3)->c_1_3<0;

constraint (p_1_3_3=4/\p_1_4_3!=4)->c_1_3<0;
constraint (p_1_3_3!=4/\p_1_4_3=4)->c_1_3<0;

constraint (p_1_3_0=5/\p_1_4_0!=5)->c_1_3<0;
constraint (p_1_3_0!=5/\p_1_4_0=5)->c_1_3<0;

constraint (p_1_3_3=6/\p_1_4_3!=6)->c_1_3<0;
constraint (p_1_3_3!=6/\p_1_4_3=6)->c_1_3<0;

constraint (p_1_3_1=7/\p_1_4_1!=7)->c_1_3<0;
constraint (p_1_3_1!=7/\p_1_4_1=7)->c_1_3<0;

constraint (p_1_3_1=8/\p_1_4_1!=8)->c_1_3<0;
constraint (p_1_3_1!=8/\p_1_4_1=8)->c_1_3<0;

constraint (p_1_3_0=9/\p_1_4_0!=9)->c_1_3<0;
constraint (p_1_3_0!=9/\p_1_4_0=9)->c_1_3<0;

constraint (p_1_3_1=10/\p_1_4_1!=10)->c_1_3<0;
constraint (p_1_3_1!=10/\p_1_4_1=10)->c_1_3<0;

constraint (p_1_3_0=11/\p_1_4_0!=11)->c_1_3<0;
constraint (p_1_3_0!=11/\p_1_4_0=11)->c_1_3<0;

constraint (p_1_3_1=12/\p_1_4_1!=12)->c_1_3<0;
constraint (p_1_3_1!=12/\p_1_4_1=12)->c_1_3<0;

constraint (p_1_3_4=13/\p_1_4_4!=13)->c_1_3<0;
constraint (p_1_3_4!=13/\p_1_4_4=13)->c_1_3<0;

constraint (p_1_3_5=14/\p_1_4_5!=14)->c_1_3<0;
constraint (p_1_3_5!=14/\p_1_4_5=14)->c_1_3<0;

constraint (p_1_3_6=15/\p_1_4_6!=15)->c_1_3<0;
constraint (p_1_3_6!=15/\p_1_4_6=15)->c_1_3<0;

constraint (p_1_3_7=16/\p_1_4_7!=16)->c_1_3<0;
constraint (p_1_3_7!=16/\p_1_4_7=16)->c_1_3<0;

constraint (p_1_3_8=17/\p_1_4_8!=17)->c_1_3<0;
constraint (p_1_3_8!=17/\p_1_4_8=17)->c_1_3<0;

% Rule 8
constraint (p_1_4_2=0/\p_1_5_2!=0)->c_1_4<0;
constraint (p_1_4_2!=0/\p_1_5_2=0)->c_1_4<0;

constraint (p_1_4_2=1/\p_1_5_2!=1)->c_1_4<0;
constraint (p_1_4_2!=1/\p_1_5_2=1)->c_1_4<0;

constraint (p_1_4_2=2/\p_1_5_2!=2)->c_1_4<0;
constraint (p_1_4_2!=2/\p_1_5_2=2)->c_1_4<0;

constraint (p_1_4_0=3/\p_1_5_0!=3)->c_1_4<0;
constraint (p_1_4_0!=3/\p_1_5_0=3)->c_1_4<0;

constraint (p_1_4_3=4/\p_1_5_3!=4)->c_1_4<0;
constraint (p_1_4_3!=4/\p_1_5_3=4)->c_1_4<0;

constraint (p_1_4_0=5/\p_1_5_0!=5)->c_1_4<0;
constraint (p_1_4_0!=5/\p_1_5_0=5)->c_1_4<0;

constraint (p_1_4_3=6/\p_1_5_3!=6)->c_1_4<0;
constraint (p_1_4_3!=6/\p_1_5_3=6)->c_1_4<0;

constraint (p_1_4_1=7/\p_1_5_1!=7)->c_1_4<0;
constraint (p_1_4_1!=7/\p_1_5_1=7)->c_1_4<0;

constraint (p_1_4_1=8/\p_1_5_1!=8)->c_1_4<0;
constraint (p_1_4_1!=8/\p_1_5_1=8)->c_1_4<0;

constraint (p_1_4_0=9/\p_1_5_0!=9)->c_1_4<0;
constraint (p_1_4_0!=9/\p_1_5_0=9)->c_1_4<0;

constraint (p_1_4_1=10/\p_1_5_1!=10)->c_1_4<0;
constraint (p_1_4_1!=10/\p_1_5_1=10)->c_1_4<0;

constraint (p_1_4_0=11/\p_1_5_0!=11)->c_1_4<0;
constraint (p_1_4_0!=11/\p_1_5_0=11)->c_1_4<0;

constraint (p_1_4_1=12/\p_1_5_1!=12)->c_1_4<0;
constraint (p_1_4_1!=12/\p_1_5_1=12)->c_1_4<0;

constraint (p_1_4_4=13/\p_1_5_4!=13)->c_1_4<0;
constraint (p_1_4_4!=13/\p_1_5_4=13)->c_1_4<0;

constraint (p_1_4_5=14/\p_1_5_5!=14)->c_1_4<0;
constraint (p_1_4_5!=14/\p_1_5_5=14)->c_1_4<0;

constraint (p_1_4_6=15/\p_1_5_6!=15)->c_1_4<0;
constraint (p_1_4_6!=15/\p_1_5_6=15)->c_1_4<0;

constraint (p_1_4_7=16/\p_1_5_7!=16)->c_1_4<0;
constraint (p_1_4_7!=16/\p_1_5_7=16)->c_1_4<0;

constraint (p_1_4_8=17/\p_1_5_8!=17)->c_1_4<0;
constraint (p_1_4_8!=17/\p_1_5_8=17)->c_1_4<0;

% Rule 8
constraint (p_1_5_2=0/\p_1_6_2!=0)->c_1_5<0;
constraint (p_1_5_2!=0/\p_1_6_2=0)->c_1_5<0;

constraint (p_1_5_2=1/\p_1_6_2!=1)->c_1_5<0;
constraint (p_1_5_2!=1/\p_1_6_2=1)->c_1_5<0;

constraint (p_1_5_2=2/\p_1_6_2!=2)->c_1_5<0;
constraint (p_1_5_2!=2/\p_1_6_2=2)->c_1_5<0;

constraint (p_1_5_0=3/\p_1_6_0!=3)->c_1_5<0;
constraint (p_1_5_0!=3/\p_1_6_0=3)->c_1_5<0;

constraint (p_1_5_3=4/\p_1_6_3!=4)->c_1_5<0;
constraint (p_1_5_3!=4/\p_1_6_3=4)->c_1_5<0;

constraint (p_1_5_0=5/\p_1_6_0!=5)->c_1_5<0;
constraint (p_1_5_0!=5/\p_1_6_0=5)->c_1_5<0;

constraint (p_1_5_3=6/\p_1_6_3!=6)->c_1_5<0;
constraint (p_1_5_3!=6/\p_1_6_3=6)->c_1_5<0;

constraint (p_1_5_1=7/\p_1_6_1!=7)->c_1_5<0;
constraint (p_1_5_1!=7/\p_1_6_1=7)->c_1_5<0;

constraint (p_1_5_1=8/\p_1_6_1!=8)->c_1_5<0;
constraint (p_1_5_1!=8/\p_1_6_1=8)->c_1_5<0;

constraint (p_1_5_0=9/\p_1_6_0!=9)->c_1_5<0;
constraint (p_1_5_0!=9/\p_1_6_0=9)->c_1_5<0;

constraint (p_1_5_1=10/\p_1_6_1!=10)->c_1_5<0;
constraint (p_1_5_1!=10/\p_1_6_1=10)->c_1_5<0;

constraint (p_1_5_0=11/\p_1_6_0!=11)->c_1_5<0;
constraint (p_1_5_0!=11/\p_1_6_0=11)->c_1_5<0;

constraint (p_1_5_1=12/\p_1_6_1!=12)->c_1_5<0;
constraint (p_1_5_1!=12/\p_1_6_1=12)->c_1_5<0;

constraint (p_1_5_4=13/\p_1_6_4!=13)->c_1_5<0;
constraint (p_1_5_4!=13/\p_1_6_4=13)->c_1_5<0;

constraint (p_1_5_5=14/\p_1_6_5!=14)->c_1_5<0;
constraint (p_1_5_5!=14/\p_1_6_5=14)->c_1_5<0;

constraint (p_1_5_6=15/\p_1_6_6!=15)->c_1_5<0;
constraint (p_1_5_6!=15/\p_1_6_6=15)->c_1_5<0;

constraint (p_1_5_7=16/\p_1_6_7!=16)->c_1_5<0;
constraint (p_1_5_7!=16/\p_1_6_7=16)->c_1_5<0;

constraint (p_1_5_8=17/\p_1_6_8!=17)->c_1_5<0;
constraint (p_1_5_8!=17/\p_1_6_8=17)->c_1_5<0;

% Rule 8
constraint (p_1_6_2=0/\p_1_7_2!=0)->c_1_6<0;
constraint (p_1_6_2!=0/\p_1_7_2=0)->c_1_6<0;

constraint (p_1_6_2=1/\p_1_7_2!=1)->c_1_6<0;
constraint (p_1_6_2!=1/\p_1_7_2=1)->c_1_6<0;

constraint (p_1_6_2=2/\p_1_7_2!=2)->c_1_6<0;
constraint (p_1_6_2!=2/\p_1_7_2=2)->c_1_6<0;

constraint (p_1_6_0=3/\p_1_7_0!=3)->c_1_6<0;
constraint (p_1_6_0!=3/\p_1_7_0=3)->c_1_6<0;

constraint (p_1_6_3=4/\p_1_7_3!=4)->c_1_6<0;
constraint (p_1_6_3!=4/\p_1_7_3=4)->c_1_6<0;

constraint (p_1_6_0=5/\p_1_7_0!=5)->c_1_6<0;
constraint (p_1_6_0!=5/\p_1_7_0=5)->c_1_6<0;

constraint (p_1_6_3=6/\p_1_7_3!=6)->c_1_6<0;
constraint (p_1_6_3!=6/\p_1_7_3=6)->c_1_6<0;

constraint (p_1_6_1=7/\p_1_7_1!=7)->c_1_6<0;
constraint (p_1_6_1!=7/\p_1_7_1=7)->c_1_6<0;

constraint (p_1_6_1=8/\p_1_7_1!=8)->c_1_6<0;
constraint (p_1_6_1!=8/\p_1_7_1=8)->c_1_6<0;

constraint (p_1_6_0=9/\p_1_7_0!=9)->c_1_6<0;
constraint (p_1_6_0!=9/\p_1_7_0=9)->c_1_6<0;

constraint (p_1_6_1=10/\p_1_7_1!=10)->c_1_6<0;
constraint (p_1_6_1!=10/\p_1_7_1=10)->c_1_6<0;

constraint (p_1_6_0=11/\p_1_7_0!=11)->c_1_6<0;
constraint (p_1_6_0!=11/\p_1_7_0=11)->c_1_6<0;

constraint (p_1_6_1=12/\p_1_7_1!=12)->c_1_6<0;
constraint (p_1_6_1!=12/\p_1_7_1=12)->c_1_6<0;

constraint (p_1_6_4=13/\p_1_7_4!=13)->c_1_6<0;
constraint (p_1_6_4!=13/\p_1_7_4=13)->c_1_6<0;

constraint (p_1_6_5=14/\p_1_7_5!=14)->c_1_6<0;
constraint (p_1_6_5!=14/\p_1_7_5=14)->c_1_6<0;

constraint (p_1_6_6=15/\p_1_7_6!=15)->c_1_6<0;
constraint (p_1_6_6!=15/\p_1_7_6=15)->c_1_6<0;

constraint (p_1_6_7=16/\p_1_7_7!=16)->c_1_6<0;
constraint (p_1_6_7!=16/\p_1_7_7=16)->c_1_6<0;

constraint (p_1_6_8=17/\p_1_7_8!=17)->c_1_6<0;
constraint (p_1_6_8!=17/\p_1_7_8=17)->c_1_6<0;

% Rule 8
constraint (p_1_7_2=0/\p_1_8_2!=0)->c_1_7<0;
constraint (p_1_7_2!=0/\p_1_8_2=0)->c_1_7<0;

constraint (p_1_7_2=1/\p_1_8_2!=1)->c_1_7<0;
constraint (p_1_7_2!=1/\p_1_8_2=1)->c_1_7<0;

constraint (p_1_7_2=2/\p_1_8_2!=2)->c_1_7<0;
constraint (p_1_7_2!=2/\p_1_8_2=2)->c_1_7<0;

constraint (p_1_7_0=3/\p_1_8_0!=3)->c_1_7<0;
constraint (p_1_7_0!=3/\p_1_8_0=3)->c_1_7<0;

constraint (p_1_7_3=4/\p_1_8_3!=4)->c_1_7<0;
constraint (p_1_7_3!=4/\p_1_8_3=4)->c_1_7<0;

constraint (p_1_7_0=5/\p_1_8_0!=5)->c_1_7<0;
constraint (p_1_7_0!=5/\p_1_8_0=5)->c_1_7<0;

constraint (p_1_7_3=6/\p_1_8_3!=6)->c_1_7<0;
constraint (p_1_7_3!=6/\p_1_8_3=6)->c_1_7<0;

constraint (p_1_7_1=7/\p_1_8_1!=7)->c_1_7<0;
constraint (p_1_7_1!=7/\p_1_8_1=7)->c_1_7<0;

constraint (p_1_7_1=8/\p_1_8_1!=8)->c_1_7<0;
constraint (p_1_7_1!=8/\p_1_8_1=8)->c_1_7<0;

constraint (p_1_7_0=9/\p_1_8_0!=9)->c_1_7<0;
constraint (p_1_7_0!=9/\p_1_8_0=9)->c_1_7<0;

constraint (p_1_7_1=10/\p_1_8_1!=10)->c_1_7<0;
constraint (p_1_7_1!=10/\p_1_8_1=10)->c_1_7<0;

constraint (p_1_7_0=11/\p_1_8_0!=11)->c_1_7<0;
constraint (p_1_7_0!=11/\p_1_8_0=11)->c_1_7<0;

constraint (p_1_7_1=12/\p_1_8_1!=12)->c_1_7<0;
constraint (p_1_7_1!=12/\p_1_8_1=12)->c_1_7<0;

constraint (p_1_7_4=13/\p_1_8_4!=13)->c_1_7<0;
constraint (p_1_7_4!=13/\p_1_8_4=13)->c_1_7<0;

constraint (p_1_7_5=14/\p_1_8_5!=14)->c_1_7<0;
constraint (p_1_7_5!=14/\p_1_8_5=14)->c_1_7<0;

constraint (p_1_7_6=15/\p_1_8_6!=15)->c_1_7<0;
constraint (p_1_7_6!=15/\p_1_8_6=15)->c_1_7<0;

constraint (p_1_7_7=16/\p_1_8_7!=16)->c_1_7<0;
constraint (p_1_7_7!=16/\p_1_8_7=16)->c_1_7<0;

constraint (p_1_7_8=17/\p_1_8_8!=17)->c_1_7<0;
constraint (p_1_7_8!=17/\p_1_8_8=17)->c_1_7<0;

% Rule 10
constraint p_1_0_0=p_2_0_0;
constraint p_1_0_1=p_2_0_1;
constraint p_1_0_2=p_2_0_2;
constraint p_1_0_3=p_2_0_3;
constraint p_1_0_4=p_2_0_4;
constraint p_1_0_5=p_2_0_5;
constraint p_1_0_6=p_2_0_6;
constraint p_1_0_7=p_2_0_7;
constraint p_1_0_8=p_2_0_8;
constraint p_1_1_0=p_2_2_0;
constraint p_1_1_1=p_2_2_1;
constraint p_1_1_2=p_2_2_2;
constraint p_1_1_3=p_2_2_3;
constraint p_1_1_4=p_2_2_4;
constraint p_1_1_5=p_2_2_5;
constraint p_1_1_6=p_2_2_6;
constraint p_1_1_7=p_2_2_7;
constraint p_1_1_8=p_2_2_8;
constraint p_1_2_0=p_2_3_0;
constraint p_1_2_1=p_2_3_1;
constraint p_1_2_2=p_2_3_2;
constraint p_1_2_3=p_2_3_3;
constraint p_1_2_4=p_2_3_4;
constraint p_1_2_5=p_2_3_5;
constraint p_1_2_6=p_2_3_6;
constraint p_1_2_7=p_2_3_7;
constraint p_1_2_8=p_2_3_8;
constraint p_1_3_0=p_2_5_0;
constraint p_1_3_1=p_2_5_1;
constraint p_1_3_2=p_2_5_2;
constraint p_1_3_3=p_2_5_3;
constraint p_1_3_4=p_2_5_4;
constraint p_1_3_5=p_2_5_5;
constraint p_1_3_6=p_2_5_6;
constraint p_1_3_7=p_2_5_7;
constraint p_1_3_8=p_2_5_8;
constraint p_1_4_0=p_2_6_0;
constraint p_1_4_1=p_2_6_1;
constraint p_1_4_2=p_2_6_2;
constraint p_1_4_3=p_2_6_3;
constraint p_1_4_4=p_2_6_4;
constraint p_1_4_5=p_2_6_5;
constraint p_1_4_6=p_2_6_6;
constraint p_1_4_7=p_2_6_7;
constraint p_1_4_8=p_2_6_8;
constraint p_1_5_0=p_2_8_0;
constraint p_1_5_1=p_2_8_1;
constraint p_1_5_2=p_2_8_2;
constraint p_1_5_3=p_2_8_3;
constraint p_1_5_4=p_2_8_4;
constraint p_1_5_5=p_2_8_5;
constraint p_1_5_6=p_2_8_6;
constraint p_1_5_7=p_2_8_7;
constraint p_1_5_8=p_2_8_8;
constraint p_1_6_0=p_2_9_0;
constraint p_1_6_1=p_2_9_1;
constraint p_1_6_2=p_2_9_2;
constraint p_1_6_3=p_2_9_3;
constraint p_1_6_4=p_2_9_4;
constraint p_1_6_5=p_2_9_5;
constraint p_1_6_6=p_2_9_6;
constraint p_1_6_7=p_2_9_7;
constraint p_1_6_8=p_2_9_8;
constraint p_1_7_0=p_2_11_0;
constraint p_1_7_1=p_2_11_1;
constraint p_1_7_2=p_2_11_2;
constraint p_1_7_3=p_2_11_3;
constraint p_1_7_4=p_2_11_4;
constraint p_1_7_5=p_2_11_5;
constraint p_1_7_6=p_2_11_6;
constraint p_1_7_7=p_2_11_7;
constraint p_1_7_8=p_2_11_8;
constraint p_1_8_0=p_2_12_0;
constraint p_1_8_1=p_2_12_1;
constraint p_1_8_2=p_2_12_2;
constraint p_1_8_3=p_2_12_3;
constraint p_1_8_4=p_2_12_4;
constraint p_1_8_5=p_2_12_5;
constraint p_1_8_6=p_2_12_6;
constraint p_1_8_7=p_2_12_7;
constraint p_1_8_8=p_2_12_8;
% Rule 11
constraint c_1_0>=0 -> c_1_0==c_2_0;
constraint c_1_1>=0 -> c_1_1==c_2_2;
constraint c_1_2>=0 -> c_1_2==c_2_3;
constraint c_1_3>=0 -> c_1_3==c_2_5;
constraint c_1_4>=0 -> c_1_4==c_2_6;
constraint c_1_5>=0 -> c_1_5==c_2_8;
constraint c_1_6>=0 -> c_1_6==c_2_9;
constraint c_1_7>=0 -> c_1_7==c_2_11;
constraint c_1_8>=0 -> c_1_8==c_2_12;
constraint c_1_0=-18 -> c_2_0=3;
constraint c_1_0=-18 -> c_2_1=0/\true;
constraint c_1_0=-19 -> c_2_0=-12\/c_2_0=-13\/c_2_0=-14\/c_2_0=-15\/c_2_0=-16\/false;
constraint c_1_0=-19 -> c_2_1=3;
constraint c_1_0=-20 -> c_2_0=7;
constraint c_1_0=-20 -> c_2_1=0/\true;
constraint c_1_0=-7 -> c_2_0=2;
constraint c_1_0=-7 -> c_2_1=0/\true;
constraint c_1_0=-8 -> c_2_0=-12\/c_2_0=-13\/c_2_0=-14\/c_2_0=-15\/c_2_0=-16\/false;
constraint c_1_0=-8 -> c_2_1=2;
constraint c_1_0=-9 -> c_2_0=5;
constraint c_1_0=-9 -> c_2_1=0/\true;
constraint c_1_0=-12 -> c_2_0=1;
constraint c_1_0=-12 -> c_2_1=0/\true;
constraint c_1_0=-13 -> c_2_0=4;
constraint c_1_0=-13 -> c_2_1=0/\true;
constraint c_1_0=-14 -> c_2_0=-7\/c_2_0=-8\/c_2_0=-9\/false;
constraint c_1_0=-14 -> c_2_1=1;
constraint c_1_0=-15 -> c_2_0=-18\/c_2_0=-19\/c_2_0=-20\/false;
constraint c_1_0=-15 -> c_2_1=4;
constraint c_1_0=-16 -> c_2_0=6;
constraint c_1_0=-16 -> c_2_1=0/\true;
constraint c_1_1=-17 -> c_2_2=10;
constraint c_1_1=-21 -> c_2_2=12;
constraint c_1_1=-10 -> c_2_2=8;
constraint c_1_2=-7 -> c_2_3=2;
constraint c_1_2=-7 -> c_2_4=0/\true;
constraint c_1_2=-8 -> c_2_3=-12\/c_2_3=-13\/c_2_3=-14\/c_2_3=-15\/c_2_3=-16\/false;
constraint c_1_2=-8 -> c_2_4=2;
constraint c_1_2=-9 -> c_2_3=5;
constraint c_1_2=-9 -> c_2_4=0/\true;
constraint c_1_3=-11 -> c_2_5=14;
constraint c_1_4=-18 -> c_2_6=3;
constraint c_1_4=-18 -> c_2_7=0/\true;
constraint c_1_4=-19 -> c_2_6=-12\/c_2_6=-13\/c_2_6=-14\/c_2_6=-15\/c_2_6=-16\/false;
constraint c_1_4=-19 -> c_2_7=3;
constraint c_1_4=-20 -> c_2_6=7;
constraint c_1_4=-20 -> c_2_7=0/\true;
constraint c_1_4=-7 -> c_2_6=2;
constraint c_1_4=-7 -> c_2_7=0/\true;
constraint c_1_4=-8 -> c_2_6=-12\/c_2_6=-13\/c_2_6=-14\/c_2_6=-15\/c_2_6=-16\/false;
constraint c_1_4=-8 -> c_2_7=2;
constraint c_1_4=-9 -> c_2_6=5;
constraint c_1_4=-9 -> c_2_7=0/\true;
constraint c_1_4=-12 -> c_2_6=1;
constraint c_1_4=-12 -> c_2_7=0/\true;
constraint c_1_4=-13 -> c_2_6=4;
constraint c_1_4=-13 -> c_2_7=0/\true;
constraint c_1_4=-14 -> c_2_6=-7\/c_2_6=-8\/c_2_6=-9\/false;
constraint c_1_4=-14 -> c_2_7=1;
constraint c_1_4=-15 -> c_2_6=-18\/c_2_6=-19\/c_2_6=-20\/false;
constraint c_1_4=-15 -> c_2_7=4;
constraint c_1_4=-16 -> c_2_6=6;
constraint c_1_4=-16 -> c_2_7=0/\true;
constraint c_1_5=-22 -> c_2_8=9;
constraint c_1_5=-24 -> c_2_8=11;
constraint c_1_5=-25 -> c_2_8=13;
constraint c_1_6=-18 -> c_2_9=3;
constraint c_1_6=-18 -> c_2_10=0/\true;
constraint c_1_6=-19 -> c_2_9=-12\/c_2_9=-13\/c_2_9=-14\/c_2_9=-15\/c_2_9=-16\/false;
constraint c_1_6=-19 -> c_2_10=3;
constraint c_1_6=-20 -> c_2_9=7;
constraint c_1_6=-20 -> c_2_10=0/\true;
constraint c_1_7=-23 -> c_2_11=19;
